config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tasks#index'
  # get 'tasks/set_tasks' => 'tasks#set_tasks'
  resources :tasks do
    resources :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy, :edit, :update], controller: 'task/comments'
  end
  resources :projects do
    resources :members, only: [:create, :destroy, :update, :index]
    resources :tasks, only: [:new]
    resources :comments, only: [:create, :destroy, :edit, :update], controller: 'project/comments'
  end

  get 'favorites' => "favorites#index"
  resources :users, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/comment/task.rb
class Comment::Task < Comment
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :favorites, :dependent => :destroy
  belongs_to :user
  has_many :comments, class_name: 'Comment::Task', as: :commentable , dependent: :destroy

  validates :deadline, :status, presence: true
  validates :title, length: { in: 1..10 } 
  validates :content, length: { in: 1..50 }

  def display_status
    case status
    when 1
      "未対応"
    when 2
      "対応中"
    when 3
      "完了"
    end
  end

  def expired?
    deadline > Time.now
  end

  def current_user?(user)
    user.id == user_id
  end

  def favorite_by?(user)
    Favorite.find_by(user_id: user.id, task_id: id)
  end

  scope :visible, -> {
    where(status: [1, 2])
  }

end

app/controllers/task/comments_controller.rb
class Task::CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: [:destroy, :update]
  before_action :set_task, only: [:create, :update, :destroy]

  def create
    @comment = @task.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:task] = 'タスクのコメントを作成しました'
      redirect_to task_path(@task)
    else
      @comments = @task.comments.where.not(id: nil)
      render 'tasks/show'
    end
  end

  def update
    if @comment.update(comment_params)
      flash[:task] = 'タスクのコメントを編集しました'
      redirect_to task_path(@task)
    else
      @comments = @task.comments.where.not(id: nil)
      render 'tasks/show'
    end
  end

  def destroy
    @comment.destroy
    flash[:task] = 'タスクのコメントを削除しました'
    redirect_to task_path(@task)
  end

  private

  def set_task
    @task = Task.find(params[:task_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(params[:type].underscore.gsub('/', '_').to_sym).permit(:content)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :show, :edit, :destroy, :update]
  before_action :set_task, only: [:show]
  before_action :set_mytask, only: [:edit, :update, :destroy]


  def index
    if params[:status] == '0' || params[:status].nil?
      @tasks = Task.all
    else
      @tasks = Task.where(status: params[:status])
    end
  end

  def new
    if params[:project_id]
      @project = Project.friendly.find(params[:project_id])
    end
    @task = Task.new
  end

  def show
    @comment = Comment::Task.new
    @comments = @task.comments
  end

  def create
    @task = Task.new(task_params)
    if params[:project_id]
      @task.project_id = params[:project_id]
    end
    if @task.save
      redirect_to @task, notice: 'タスクを作成しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    if @task.project_id
      @project = Project.find(@task.project_id)
    end
  end

  def update
    if @task.update(task_params)
      redirect_to @task, notice: 'タスクを更新しました'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to root_path, notice: 'タスクを削除しました'
  end

  def assign
  end

  def set_edit_task
    @task = Task.find(params[:task_id])
    @users = @task.users.order(:id)
  end

  def team_select
    @users = @team.users
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def set_team
    @project = Project.find_by(id: @task.team_id)
  end

  def set_mytask
    @task = current_user.tasks.find(params[:id])
  end


  def task_params
    params.require(:task).permit(:title, :content, :deadline, :status, :user_id)
  end

end

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= form_with(model: task, local: true, id: :form) do |form| %>
      <% if task.errors.any? %>
        <div class="alert-danger", id="error_explanation">
          <ul>
            <% task.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form_group">
        <div class="field">
          <%= form.label :title %>
          <%= form.text_field :title, class:"col-lg-12 form-control" %>
        </div>
      </div>

      <div class="form_group">
        <div class="field">
          <%= form.label :content %>
          <%= form.text_field :content, class:"col-lg-12 form-control" %>
        </div>
      </div>

      <%if @project %>
        <div class="form_group">
          <div class="field">
            <%= form.label :user_id %>
            <%= form.collection_select :user_id, @project.users, :id, :name, {prompt: "選択してください"}, :class => 'col-lg-12 form-control mb-1' %>
            <%= form.hidden_field :project_id, value: @project.id, name: 'project_id' %> 
          </div>
        </div>
      <% else %> 
        <%= form.hidden_field :user_id, value: current_user.id%> 
      <% end %> 

      <%= form.label :deadline %><br>
      <div class="input-group form_group" data-target-input="nearest">

        <%= form.text_field :deadline, id: "deadline", value: DateTime.now.to_s(:datetime), class: "form-control datepicker", data: { target: '#deadline'} %>
        <div class="input-group-append" data-target="#deadline" data-toggle="datetimepicker">
          <div class="input-group-text"><i class="fa fa-calendar"></i></div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-1 pl-0">
          <%= form.label :status, '状態', {class: 'form-label'} %>
        </div>
        <div class="col-sm-10 pl-0 btn-group btn-group-toggle" data-toggle="buttons">
          <label class="btn btn-outline-secondary  <%= 'active' if task.status == 1 %> " style="width:30%">
            <%= form.radio_button :status, "1" %>未対応
          </label>
          <% unless task.id.nil? %>
            <label class="btn btn-outline-secondary <%= 'active' if task.status == 2 %>" style="width:30%">
              <%= form.radio_button :status, "2", class:"label" %>対応中
            </label>
          <% end %>
          <label class="btn btn-outline-secondary <%= 'active' if task.status == 3 %>" style="width:30%">
            <%= form.radio_button :status, "3" %>対応済
          </label>
        </div>
      </div>


      <div class="actions">
        <%= form.submit '登録する', class: "btn btn-success mt-2", id: "task_submit", onclick: "DisabledFalse()" %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<div class="row">
  <div class="col-lg-6">
    <div class="cp_tooltip">
        <i class="far fa-question-circle" id="question"></i>
        <span class="cp_tooltiptext">
          期限切れのタスクは赤、期限がまだのやつは緑で表示<br>
          自分のタスクは<i class="fas fa-star"></i>マークがある<br>
          プロジェクトタスクは右上にプロジェクト名がある
        </span>
    </div>
    <div class="hidden_box">
      <label for="label1"><i class="far fa-question-circle"></i></label>
      <input type="checkbox" id="label1"/>
      <div class="hidden_show">
        <span class="cp_tooltiptext">
          期限切れのタスクは赤、期限がまだのやつは緑で表示<br>
          自分のタスクは<i class="fas fa-star"></i>マークがある<br>
          プロジェクトタスクは右上にプロジェクト名がある
        </span>
      </div>
    </div>
    <h1 class="task-index">Task List</h1>
  </div>
  <div class="form-group btn-group col-lg-6 p-3">
    <%= link_to 'すべて', tasks_path(status: 0), class: "btn btn-outline-secondary tab-status #{'active' if params[:status] == '0' || params[:status].nil?} "%>
    <%= link_to '未対応', tasks_path(status: 1), class: "btn btn-outline-secondary tab-status #{'active' if params[:status] == '1'} " %>
    <%= link_to '対応中', tasks_path(status: 2), class: "btn btn-outline-secondary tab-status #{'active' if params[:status] == '2'} " %>
    <%= link_to '対応済', tasks_path(status: 3), class: "btn btn-outline-secondary tab-status #{'active' if params[:status] == '3'} " %>
  </div>
</div>
<div class="row">
  <% @tasks.each do |task| %>
      <div class="col-lg-6 pr-3 pb-3">
        <% if task.expired? %>
          <div class="card border-success">
            <div class="card-header bg-success">
        <% else %>
          <div class="card border-danger">
            <div class="card-header bg-danger">
        <% end %>
        <% if task.user == current_user %>
          <i class="fas fa-star"></i>
        <% end %>
          <%= task.title %>
        <% unless task.project_id.nil? %>
          <div class="project-name"><%= Project.where(id: task.project_id).first.name %></div>
        <% end %>
          </div>
          <div class="card-body">
            <p><%= task.content.truncate(35) %></p>
            <p>期限：<%= task.deadline.strftime("%Y年%m月%d日") %></p>
            <p>担当者：<%= link_to task.user.name, user_path(task.user), class:"no-link" %></p>
            <p>ステータス：<%= task.display_status %></p>
            <div>
              <%= link_to "詳細", task_path(task), class: "btn btn-light" %>
            </div>
          </div>
        </div>
    </div>
  <% end %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<div class="card bg-light col-lg-10 offset-md-1 mb-5 mt-5">
  <div class="card-body">
    <h2>
      <%= @task.title %>
    </h2>
    <p><%= @task.content %></p>
    <p>期限：<%= @task.deadline.strftime("%Y-%m-%d %H:%M:%S") %></p>
    <p>担当者：<%= link_to @task.user.name, user_path(@task.user), class:"no-link" %></p>
    <% unless @task.project_id.nil? %>
      <P>プロジェクト：<%= link_to Project.find(@task.project_id).name, project_path(@task.project_id), class:"no-link" %></P>
    <% end %>
    
    <p>ステータス：<%= @task.display_status %></p>
    <%= link_to '一覧へ戻る', root_path, class: "btn btn-light" %>
    <% if @task.favorite_by?(current_user) %>
      <%= link_to '保存解除',task_favorite_path(@task, @task.favorite_by?(current_user)), method: :delete, data: { confirm: '本当に解除しますか?',cancel: 'やめる',
      commit: '解除する'}, title: '保存解除確認', class: "btn btn-success" %>
    <% else %>
      <%= link_to '保存する', task_favorites_path(@task),method: :post, class: "btn btn-success" %>
    <% end %>
    <%if @task.current_user?(current_user) %>
      <%= link_to '編集', edit_task_path(@task), class: "btn btn-info" %>
      <%= link_to '削除', task_path(@task), class: "btn btn-danger", method: :delete %>
    <% end %>
  </div>
</div>

<div class="col-lg-10 offset-md-1 mb-5 mt-5 border-secondary">
  <p><i class="fas fa-comment"></i>comment</p>
  <% @comments.each_with_index do |comment, i|  %>
    <div class="box clearfix col-lg-10 offset-md-1">
      <% if comment.user == current_user %>
        <div class="mycomment">
          <div class="n<%=i%>" id="show-mode">
            <div class="my-say">
              <p><%= comment.content %></p>
              <div class="link">
              <button type="button" id="edit-mode_<%=i%>" class="btn-light edit-comment">編集</button>
                <%= link_to '削除', task_comment_path(task_id: @task.id, id: comment.id), method: :delete, data: { confirm: '本当に削除しますか?',cancel: 'やめる',
                  commit: '削除する'}, class:"btn-light delete-comment" %>
              </div>
            </div>
          </div>
          <div class="e<%=i%>" id="edit-mode">
            <div class="my-say"> 
              <%= form_for(comment, url: task_comment_path(task_id: @task.id,id: comment.id, :anchor => 'comment-new')) do |f| %>
                <%= f.text_area :content, class:"col-lg-10 offset-md-1 js-count"%>
                <%= hidden_field_tag :type, comment.type %>
                <%= f.submit '編集する', class: "col-lg-10 offset-md-1 btn btn-outline-dark mb-2 submit-edit"%>
              <% end %>
            </div>
          </div>
        </div>
      <% else %>
        <div class="comment-name ">
          <div class="edit-comment"></div>
          <div class="faceicon">
            <p class="comment-user-name"><%= comment.user.name %></p>
          </div>
          <div class="chatting">
            <div class="comment-top">
              <p><%= comment.content %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %> 
  <div class="comment-new" id="comment-new">
    <%= form_for @comment, url: task_comments_path(task_id: @task.id, :anchor => 'comment-new') do |f| %>
      <% if flash[:task] %>
        <div id="alert">
          <p class="alert-success col-lg-10 offset-md-1", id="notice"><%= flash[:task] %></p>
        </div>
      <% end %>
      <% if @comment.errors.any? %>
        <div class="alert-danger col-lg-10 offset-md-1", id="error_explanation">
          <% @comment.errors.full_messages.each do |message| %>
            <p><%= message %></p>
          <% end %>
        </div>
      <% end %> 
      <%= f.text_area :content, class:"col-lg-10 offset-md-1", placeholder:"50文字以内で入力してください" %>
      <%= hidden_field_tag :type, @comment.type %>
      <%= f.submit 'コメント', class: "col-lg-10 offset-md-1 btn btn-outline-dark mb-2"%>
    <% end %>
  </div>
</div>