config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tasks#index'
  # get 'tasks/set_tasks' => 'tasks#set_tasks'
  resources :tasks do
    resources :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy, :edit, :update], controller: 'task/comments'
  end
  resources :projects do
    resources :members, only: [:create, :destroy, :update, :index]
    resources :tasks, only: [:new]
    resources :comments, only: [:create, :destroy, :edit, :update], controller: 'project/comments'
  end

  get 'favorites' => "favorites#index"
  resources :users, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  #自分が作ったタスク
  has_many :tasks, :dependent => :destroy
  #自分が作ったプロジェクト
  has_many :myprojects, class_name: 'Project', :dependent => :destroy
  #自分が所属しているプロジェクト
  has_many :members, :dependent => :destroy
  has_many :projects, through: :members, source: :project, :dependent => :destroy
  #タスクの保存
  has_many :favorites, :dependent => :destroy
  #コメント
  has_many :comments, :dependent => :destroy
  has_many :team_comments, :dependent => :destroy
  validates :name, length: { in: 1..10 }

  def self.search(search)
    return nil unless search
    User.where(['name LIKE ?', "%#{search}%"])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show]
  before_action :set_tasks, only: [:show]

  private

  def set_user
    @user = User.find(params[:id])
  end

  def set_tasks
    if params[:status] == '0' || params[:status].nil?
      @tasks = @user.tasks.all
    else
      @tasks = current_user.tasks.where(status: params[:status])
    end
  end
end

app/views/users/show.html.erb
<div class="row">
  <div class="col-lg-6">
    <% if @user == current_user %>
      <h1>My Task</h1>
    <% else %>
      <h1> <%= @user.name %> Task </h1>
    <% end %>
  </div>
  <div class="form-group btn-group col-lg-6 p-3">
      <%= link_to 'すべて', user_path(id: current_user.id, status: 0), class: "btn btn-outline-secondary tab-status #{'active' if params[:status] == '0' || params[:status].nil?} "%>
      <%= link_to '未対応', user_path(id: current_user.id, status: 1), class: "btn btn-outline-secondary tab-status #{'active' if params[:status] == '1'} " %>
      <%= link_to '対応中', user_path(id: current_user.id, status: 2), class: "btn btn-outline-secondary tab-status #{'active' if params[:status] == '2'} " %>
      <%= link_to '対応済', user_path(id: current_user.id, status: 3), class: "btn btn-outline-secondary tab-status #{'active' if params[:status] == '3'} " %>
  </div>
</div>
<%= link_to "New Task", new_task_path, class:"btn btn-light col-lg-12 mb-3" %>

<div class="row">
  <% @tasks.each do |task| %>
    <div class="col-lg-6">
      <div class="mb-3">
        <% if task.expired? %>
          <div class="card border-success">
            <div class="card-header bg-success">
        <% else %>
          <div class="card border-danger">
            <div class="card-header bg-danger">
        <% end %>
            <%= task.title %>
            <% unless task.project_id.nil? %>
              <div class="project-name"><%= Project.where(id: task.project_id).first.name %></div>
            <% end %>
          </div>
          <div class="card-body">
            <p><%= task.content.truncate(35) %></p>
            <p>期限：<%= task.deadline.strftime("%Y年%m月%d日") %></p>
            <p>担当者：<%= link_to task.user.name, user_path(task.user), class:"no-link"%></p>
            <p>ステータス：<%= task.display_status %></p>
            <div>
              <%= link_to "詳細", task_path(task), class:"btn btn-light" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>