config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tasks#index'
  # get 'tasks/set_tasks' => 'tasks#set_tasks'
  resources :tasks do
    resources :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy, :edit, :update], controller: 'task/comments'
  end
  resources :projects do
    resources :members, only: [:create, :destroy, :update, :index]
    resources :tasks, only: [:new]
    resources :comments, only: [:create, :destroy, :edit, :update], controller: 'project/comments'
  end

  get 'favorites' => "favorites#index"
  resources :users, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/comment/project.rb
class Comment::Project < Comment
end

app/models/project.rb
class Project < ApplicationRecord
  include FriendlyId
  friendly_id :name, :use => :slugged
  has_many :members, dependent: :destroy
  has_many :users, through: :members, source: :user, dependent: :delete_all
  has_many :tasks
  has_many :comments, class_name: 'Comment::Project', as: :commentable, dependent: :destroy
  belongs_to :user, foreign_key: 'created_by'
  validates :name, length: { in: 1..15 }
  validates :description, length: { in: 1..50 }
  validates :name, uniqueness: true

  def teamed?(user)
    Member.find_by(user_id: user.id, project_id: id).present?
  end
  def normalize_friendly_id(string)
    string.gsub(/[\.\s]/, "-")
  end
  def should_generate_new_friendly_id?
    name_changed? || super
  end
  def self.search(search)
    return nil unless search
    Project.where(['name LIKE ?', "%#{search}%"])
  end
end

app/controllers/project/comments_controller.rb
class Project::CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:create, :destroy, :update]
  before_action :set_comment, only: [:destroy, :update]

  def create
    @comment = @project.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:notice] = 'プロジェクトのコメントを作成しました'
      redirect_to project_path(@project)
    else
      @tasks = Task.where(project_id: @project.id)
      @users = User.where.not(id: @project.user_ids).limit(3)
      @comments = @project.comments.where.not(id: nil)
      render 'projects/show'
    end
  end

  def update
    if @comment.update(comment_params)
      flash[:notice] = 'プロジェクトのコメントを編集しました'
      redirect_to project_path(@project)
    else
      @comments = @project.comments.where.not(id: nil)
      render 'projects/show'
    end
  end

  def destroy
    @comment.destroy
    flash[:notice] = 'プロジェクトのコメントを削除しました'
    redirect_to project_path(@project)
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(params[:type].underscore.gsub('/', '_').to_sym).permit(:content)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :destroy, :edit, :update]

  def index
    @admin_projects = Project.where(created_by: current_user)
    @projects = current_user.projects
    @new_projects = Project.limit(10).order("created_by DESC")
    if params[:search].present?
      @project = Project.search(params[:search])
      if @project.empty?
        @project = []
      end
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.created_by = current_user.id
    if @project.save
      member = Member.new(user_id: current_user.id, project_id: @project.id)
      member.save
      redirect_to project_path(@project), notice: 'プロジェクトを作成しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    unless @project.user == current_user
      redirect_to project_path(@project)
    end
  end

  def show
    if params[:status] == '0' || params[:status].nil?
      @tasks = Task.where(project_id: @project.id)
    else
      @tasks = Task.where(project_id: @project.id, status: params[:status])
    end
    @comment = Comment::Project.new
    @comments = @project.comments
    if params[:search].present?
      @users = User.search(params[:search])
    else
      @users = User.where.not(id: @project.user_ids).limit(3)
      if @users.empty?
        @users = nil
      end
    end
  end

  def update
    if @project.update(project_params)
      redirect_to project_path(@peoject), notice: 'プロジェクトを編集しました'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @project.destroy
      redirect_to projects_path, notice: 'プロジェクトを削除しました'
    else
      render :index, status: :unprocessable_entity
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :description)
  end

  def set_project
    @project = Project.friendly.find(params[:id])
  end
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/projects/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= form_for(project) do |f| %>
    <% if project.errors.any? %>
        <div class="alert-danger", id="error_explanation">
          <ul>
            <% project.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form_group">
        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name, class:"col-lg-12 form-control"%>
        </div>
      </div>
      <div class="form_group">
        <div class="field">
          <%= f.label :description %>
          <%= f.text_area :description, class:"col-lg-12 form-control" %>
        </div>
      </div>
      <%= f.submit'登録する', class: "btn btn-success mt-2" %>
    <% end %>
  </div>
</div>

app/views/projects/_show.html.erb
<div class="col-lg-6 project-tema">
  <div class="card bg-light mb-3">
    <div class="card-body">
      <div class="row">
        <div class="col-lg-8">
          <div>
            Description：<%= project.description %>
          </div>
          <div>
            管理者：<%= project.user.name %>
          </div>
          <div>
            メンバー：
            <% project.users.each_with_index do |user, i| %>
              <%= link_to user.name, user_path(user), class:"no-link" %>
              <% unless i == project.users.length - 1 %>
                ／
              <% end %>
            <% end %>
          </div>
        </div>
        <% if project.user == current_user %>
          <div class="col-lg-4">
            <%= link_to '編集', edit_project_path(project), class: "btn btn-info mt-2" %>
            <%= link_to '削除', project_path(project), method: :delete, data: { confirm: '本当に削除しますか?',cancel: 'やめる',commit: '削除する'}, title: '削除確認', class: "btn btn-danger mt-2" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div> 

app/views/projects/_task.html.erb
    <% per_tasks.each do |task| %>
      <div class="pb-3">
        <% if task.expired? %>
          <div class="card border-danger">
            <div class="card-header bg-danger">
        <% else %>
          <div class="card border-success">
            <div class="card-header bg-success">
        <% end %>
              <%= task.title %>
            </div>
        <div class="card-body">
          <p><%= task.content %></p>
          <p>期限：<%= task.deadline.strftime("%Y年%m月%d日") %></p>
          <p>担当者：<%= link_to task.user.name, user_path(task.user), class:"no-link"%></p>
          <p>ステータス：<%= task.display_status %></p>
          <div>
            <%= link_to "詳細", task_path(task), class: "btn btn-light" %>
            <% if task.user == current_user %>
              <%= link_to "編集", edit_task_path(task), class: "btn btn-info" %>
              <%= link_to "削除", task_path(task), method: :delete, data: { confirm: '本当に削除しますか?',cancel: 'やめる',
                    commit: '削除する'}, title: '削除確認', class: "btn btn-danger" %>
            <% end %>
          </div>
        </div>
        </div>
      </div>
    <% end %>

app/views/projects/edit.html.erb
<h1>Edit Team</h1>

<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<h1>Project Page</h1>
<div class="row">
  <div class="col-lg-8">
    <div class="mb-4">
      <%= form_tag(projects_path,:method => 'get') do %>
        <div class="input-group mb-2">
          <%= text_field_tag :search, '', :placeholder =>'プロジェクト検索', :class => 'form-control' %>
          <span class="input-group-btn">
            <%= button_tag :name => nil, type: 'submit', class: "btn btn-success search-button" do %>
              <i class="fas fa-search"></i>
            <% end %>
          </span>
        </div>
      <% end %>
      <% unless @project.nil? %>
        <% if @project.empty? %>
          存在しないプロジェクト名です。
        <% else %>
          <div class="row">
            <div class="col-lg-12 pr-0">
              <h4>検索結果</h4>
            </div>
            <% @project.each do |project| %>
              <div class="col-lg-3 pr-0">
                <div class=" mb-3 mr-3">
                  <div class="card border-primar">
                    <div class="card-body">
                      <p>Name : <%= project.name.truncate(10) %></p>
                      <p>Description : <%= project.description.truncate(20) %></p>
                      <%= link_to '詳細', project_path(project), class:"btn btn-light" %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="col-lg-4">
    <%= link_to "プロジェクトを作成する", new_project_path, class:"btn btn-info col-lg-12 mb-4" %>
  </div>
</div>

<div class="row">
  <div class="col-lg-4">
    <% if @admin_projects.present? %>
      <h5>管理者のプロジェクト一覧</h5>
      <div class="row">
        <% @admin_projects.each do |myproject|%>
          <div class="col-lg-12 pr-0">
            <div class="mr-3 mb-3">
              <div class="card border-success">
                <div class="card-body">
                  <p>Name : <%= myproject.name.truncate(10) %></p>
                  <p>Description : <%= myproject.description.truncate(20) %></p>
                  <%= link_to '詳細', project_path(myproject), class:"btn btn-light" %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="col-lg-4">
    <% if @projects.present? %>
      <h5>入っているプロジェクトの一覧</h5>
      <div class="row">
        <% @projects.each do |project| %>
          <div class="col-lg-12">
            <div class="mr-3 mb-3">
              <div class="card border-success">
                <div class="card-body">
                  <p>Name : <%= project.name.truncate(10) %></p>
                  <p>Description : <%= project.description.truncate(20) %></p>
                  <%= link_to '詳細', project_path(project), class:"btn btn-light" %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>




<div class="col-lg-4">
  
  <% if @new_projects.present? %>
    <h5>新しいプロジェクトの一覧</h5>
    <div class="row">
      <% @new_projects.each do |project| %>
        <div class="col-lg-12">
          <div class="mb-3">
            <div class="card border-success">
              <div class="card-body">
                <p>Name : <%= project.name.truncate(10) %></p>
                <p>Description : <%= project.description.truncate(20) %></p>
                <%= link_to '詳細', project_path(project), class:"btn btn-light" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/projects/new.html.erb
<h1>Create Team</h1>

<%= render 'form',project: @project %>

app/views/projects/show.html.erb
<div class="col-lg-12">
  <h2><%= @project.name%> Project Page</h2>
</div>
<% if @project.user == current_user %>
  <div class="row project-top">
    <div class="col-lg-6"> 
      <p>ユーザーの追加</p>
      <%= form_tag(project_path(@project),:method => 'get') do %>
        <div class="input-group mb-2">
          <%= text_field_tag :search, '', :placeholder =>'ユーザ検索', :class => 'form-control' %>
          <span class="input-group-btn">
            <%= button_tag :name => nil, type: 'submit', class: "btn btn-success" do %>
              <i class="fas fa-search"></i>
            <% end %>
          </span>
        </div>
      <% end %>
      <% unless @users.nil? %>
        <% unless @users.empty? %>
          <div class="project-add-user">
            <div class="cp_tooltip"><i class="far fa-question-circle" id="question"></i>
              <span class="cp_tooltiptext">
                ユーザー検索で追加したいユーザーを検索できるよ<br>
                追加ボタンを押すとユーザーをプロジェクトに追加できるよ
              </span>
            </div>
            <div class="hidden_box">
              <label for="label1"><i class="far fa-question-circle"></i></label>
              <input type="checkbox" id="label1"/>
              <div class="hidden_show">
                <span class="cp_tooltiptext">
                  ユーザー検索で追加したいユーザーを検索できるよ<br>
                  追加ボタンを押すとユーザーをプロジェクトに追加できるよ
                </span>
              </div>
            </div>
            <% @users.each_with_index do |user, i| %>
              <% unless user == current_user %>
                <%= link_to user.name, user_path(user), class:"btn-sticky" %>
                <% if @project.teamed?(user) %>
                  追加済み
                <% else %>
                  <%= link_to '追加', project_members_path(@project, user_id: user.id), method: :post, class: 'btn-light' %>
                <% end %>
              <% end %>
              <% unless i == @users.length - 1 %>
                ／
              <% end %>
            <% end %>
          </div>
        <% else %>
          そのユーザーはいないです
        <% end %>
      <% end %>
  </div>
  <%= render 'show', project: @project %>
</div>
<div class="row">
  <div class="col-lg-6">
      <%= link_to "プロジェクトタスク作成", new_project_task_path(@project), class:"btn btn-info col-lg-12 mb-4" %>
    <div class="form-group btn-group col-lg-12 p-0">      
        <%= link_to 'すべて', project_path(id: @project.id, status: 0), class: "btn btn-outline-secondary tab-status #{'active' if params[:status] == '0' || params[:status].nil?} "%>
        <%= link_to '未対応', project_path(id: @project.id, status: 1), class: "btn btn-outline-secondary tab-status #{'active' if params[:status] == '1'} " %>
        <%= link_to '対応中', project_path(id: @project.id, status: 2), class: "btn btn-outline-secondary tab-status #{'active' if params[:status] == '2'} " %>
        <%= link_to '対応済', project_path(id: @project.id, status: 3), class: "btn btn-outline-secondary tab-status #{'active' if params[:status] == '3'} " %> 
    </div>
    <%= render 'task', per_tasks: @tasks %>
  </div>
  
  <div class="col-lg-6 comment-project border-secondary">
    <p><i class="fas fa-comment"></i>comment</p>
    <% @comments.each_with_index do |comment, i| %>
      <div class="box clearfix col-lg-10 offset-md-1">
        <% if comment.user == current_user %>
          <div class="mycomment">
            <div class="n<%=i%>" id="show-mode">
              <div class="my-say">
                <p><%= comment.content %></p>
                <div class="link">
                <button type="button" id="edit-mode_<%=i%>" class="btn-light edit-comment">編集</button>
                  <%= link_to '削除', project_comment_path(project_id: @project.id, id: comment.id), method: :delete, data: { confirm: '本当に削除しますか?',cancel: 'やめる',
                    commit: '削除する'}, class:"btn-light delete-comment" %>
                </div>
              </div>
            </div>
            <div class="e<%=i%>" id="edit-mode">
              <div class="my-say"> 
                <%= form_for(comment, url: project_comment_path(project_id: @project.id,id: comment.id, :anchor => 'comment-new')) do |f| %>
                  <%= f.text_area :content, class:"col-lg-10 offset-md-1 js-count"%>
                  <%= hidden_field_tag :type, comment.type %>
                  <%= f.submit '編集する', class: "col-lg-10 offset-md-1 btn btn-outline-dark mb-2 submit-edit"%>
                <% end %>
              </div>
            </div>
          
          </div>
        <% else %>
          <div class="comment-name ">
            <div class="edit-comment"></div>
            <div class="faceicon">
              <p class="comment-user-name"><%= comment.user.name %></p>
            </div>
            <div class="chatting">
              <div class="comment-top">
                <p><%= comment.content %></p>
              </div>
            </div>
        </div>
        <% end %>
      </div>
  <% end %>  
  <div class="comment-new">
      <%= form_for @comment, url: project_comments_path(project_id: @project.id) do |f| %>
        <%= f.text_area :content, class:"col-lg-10 offset-md-1 project-comment-form" %>
        <%= hidden_field_tag :type, @comment.type %>
        <%= f.submit 'コメント', class: "col-lg-10 offset-md-1 btn btn-outline-dark mb-2"%>
      <% end %>
    </div>
  </div>
</div>
<% else %>
  <div class="row project-top">
    <div class="col-lg-6 p-3"> 
    <%= link_to "プロジェクトタスク作成", new_project_task_path(@project), class:"btn btn-info col-lg-12 mb-4" %>
    <div class="form-group btn-group col-lg-12 p-0">      
        <%= link_to 'すべて', project_path(id: @project.id, status: 0), class: "btn btn-outline-secondary tab-status #{'active' if params[:status] == '0' || params[:status].nil?} "%>
        <%= link_to '未対応', project_path(id: @project.id, status: 1), class: "btn btn-outline-secondary tab-status #{'active' if params[:status] == '1'} " %>
        <%= link_to '対応中', project_path(id: @project.id, status: 2), class: "btn btn-outline-secondary tab-status #{'active' if params[:status] == '2'} " %>
        <%= link_to '対応済', project_path(id: @project.id, status: 3), class: "btn btn-outline-secondary tab-status #{'active' if params[:status] == '3'} " %> 
    </div>
  </div>
  <%= render 'show', project: @project %>
</div>
<div class="row">
  <div class="col-lg-6">
    <%= render 'task', per_tasks: @tasks %>
  </div>
  
  <div class="col-lg-6 comment-project border-secondary">
    <p><i class="fas fa-comment"></i>comment</p>
    <% @comments.each_with_index do |comment, i| %>
      <div class="box clearfix col-lg-10 offset-md-1">
        <% if comment.user == current_user %>
          <div class="mycomment">
            <div class="n<%=i%>" id="show-mode">
              <div class="my-say">
                <p><%= comment.content %></p>
                <div class="link">
                <button type="button" id="edit-mode_<%=i%>" class="btn-light edit-comment">編集</button>
                  <%= link_to '削除', project_comment_path(project_id: @project.id, id: comment.id), method: :delete, data: { confirm: '本当に削除しますか?',cancel: 'やめる',
                    commit: '削除する'}, class:"btn-light delete-comment" %>
                </div>
              </div>
            </div>
            <div class="e<%=i%>" id="edit-mode">
              <div class="my-say"> 
                <%= form_for(comment, url: project_comment_path(project_id: @project.id,id: comment.id, :anchor => 'comment-new')) do |f| %>
                  <%= f.text_area :content, class:"col-lg-10 offset-md-1 js-count"%>
                  <%= hidden_field_tag :type, comment.type %>
                  <%= f.submit '更新する', class: "col-lg-10 offset-md-1 btn btn-outline-dark mb-2 submit-edit"%>
                <% end %>
              </div>
            </div>
          
          </div>
        <% else %>
          <div class="comment-name ">
            <div class="edit-comment"></div>
            <div class="faceicon">
              <p class="comment-user-name"><%= comment.user.name %></p>
            </div>
            <div class="chatting">
              <div class="comment-top">
                <p><%= comment.content %></p>
              </div>
            </div>
        </div>
        <% end %>
      </div>
  <% end %>  
  <div class="comment-new">
      <%= form_for @comment, url: project_comments_path(project_id: @project.id) do |f| %>
        <%= f.text_area :content, class:"col-lg-10 offset-md-1 project-comment-form", placeholder:"50文字以内で入力してください" %>
        <%= hidden_field_tag :type, @comment.type %>
        <%= f.submit 'コメント', class: "col-lg-10 offset-md-1 btn btn-outline-dark mb-2"%>
      <% end %>
    </div>
  </div>
</div>
<% end %>