config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'tasks#index'
  # get 'tasks/set_tasks' => 'tasks#set_tasks'
  resources :tasks do
    resources :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy, :edit, :update], controller: 'task/comments'
  end
  resources :projects do
    resources :members, only: [:create, :destroy, :update, :index]
    resources :tasks, only: [:new]
    resources :comments, only: [:create, :destroy, :edit, :update], controller: 'project/comments'
  end

  get 'favorites' => "favorites#index"
  resources :users, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <%= link_to 'タスク管理アプリ', root_path, class:"navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <% if user_signed_in? %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to 'マイタスク', user_path(current_user), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to '保存したタスク一覧', favorites_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'プロジェクト', projects_path, class: "nav-link" %>
            </li>

          </ul>
          <div class="navbar-text navbar-right">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  ようこそ<%= current_user.name %>さん
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <%= link_to 'ユーザ設定',edit_user_registration_path, class:"dropdown-item nav-link", style:"color: #000000;"%>
                  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete,class:"dropdown-item nav-link", data: { confirm: '本当にログアウトしますか?',cancel: 'やめる',
                  commit: 'ログアウトする'}, title: 'ログアウトの確認', style:" color: #000000;"%>
                </div>
              </li>
            </ul>
          </div>
        </div>
      <% else %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to 'マイタスク', new_user_session_path, class: "nav-link" %>
            </li>
          </ul>
          <div class="navbar-text navbar-right">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <%= link_to 'サインイン', new_user_session_path, class: "nav-link" %>
              </li>
              <li>
                <%= link_to 'サインアップ', new_user_registration_path, class: "nav-link" %>
              </li>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>タスク</title>
    <%= favicon_link_tag 'book_character_smile.png'%>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>
    <%= render 'layouts/header' %>
    <div id="alert">
      <p class="alert-success text-center", id="notice"><%= notice %></p>
    </div>
    <% if @comment && @comment.errors.any? %>
    <div class="alert-danger text-center", id="error_explanation">
      <% @comment.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>